### ISSUE TITLE
ライセンスを考える

### ISSUE THREAD

**Issue by nunnun** [cns-consultant/endeavour#7]
コードのライセンスを考える必要があります。  
すでにCode Contributionしている @kentosasa @reatgcr0wn が良ければMITライセンスにしようかなと思いますが、いかがでしょうか？

**Comment by reatgcr0wn** [comment]
僕はMITで大丈夫だと思います！

岡本
2016/02/09 17:29 "Hirotaka Nakajima" <notifications@github.com>:

**Comment by kentosasa** [comment]
MITで問題ないです。

**Comment by nunnun** [comment]
ありがとうございます。
ではMITにしたいと思います。

**Comment by nunnun** [comment]
#8 でpull reqしてます

**Comment by nunnun** [comment]
マージしたのでクローズ
